# Generated by Django 4.1.3 on 2023-01-01 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_comment_body'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-created', '-updated')},
        ),
    ]
